<h1>Episodios Cards</h1>
<div class="row episodes"></div>
<hr>
<div class="row episodesTable"></div>
<h1>Episodios DataTable</h1>

    <div class="post-search-panel">
        
        
    </div>
    <table class="striped purple accent-3" id="episodiosTabla" cellspacing="0">
        
        <thead class="thead-light">
        <tr class="text-white">
            <th>ID</th>
            <th>Fecha de Emisión</th>
            <th>Episodo</th>
            <th>Nombre</th>
            <th>Número de Personajes</th>
            <th>URL</th>
        </tr>
        </thead>
    </table>
