<h1 class="text-center">Episodios</h1>
<div class="row mt-5">
    <div class="col-6">
        <img src="img/index-00.jpg" alt="" class="img-fluid">
    </div>
    <div class="col-6">
        <div class="row">
            <div class="col-12">
                <img src="img/index-01.jpg" alt="" class="img-fluid">
            </div>
            <div class="col-12 mt-3">
                <img src="img/index-02.jpg" alt="" class="img-fluid">
            </div>
        </div>
    </div>
</div>