<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["episodes", "Atrás"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Editar episodios</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="episodes/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldAirDate" class="col-sm-2 control-label">Fecha de emisión</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["air_date", "size" => 30, "class" => "form-control", "id" => "fieldAirDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEpisode" class="col-sm-2 control-label">Episodo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["episode", "size" => 30, "class" => "form-control", "id" => "fieldEpisode"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCharacters" class="col-sm-2 control-label">Nº personajes</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["characters", "type" => "number", "class" => "form-control", "id" => "fieldCharacters"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUrl" class="col-sm-2 control-label">Url</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["url", "size" => 30, "class" => "form-control", "id" => "fieldUrl"]) ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
