<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Buscar episodios</h1>
    <p><?php echo $this->tag->linkTo(["episodes/new", "Crear episodios"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="episodes/search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAirDate" class="col-sm-2 control-label">Fecha de emisión</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["air_date", "size" => 30, "class" => "form-control", "id" => "fieldAirDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEpisode" class="col-sm-2 control-label">Episodo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["episode", "size" => 30, "class" => "form-control", "id" => "fieldEpisode"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCharacters" class="col-sm-2 control-label">Nº de personajes</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["characters", "type" => "number", "class" => "form-control", "id" => "fieldCharacters"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUrl" class="col-sm-2 control-label">Url</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["url", "size" => 30, "class" => "form-control", "id" => "fieldUrl"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
